[package]
name = "cat"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["cargo"] }

[dev-dependencies]
assert_cmd = "2.1.1"
assert_fs = "1.1.3"
predicates = "3.1.3"
