[package]
name = "md5sum"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["cargo"] }
md5 = "0.8.0"

[dev-dependencies]
assert_cmd = "2.1.2"
assert_fs = "1.1.3"
predicates = "3.1.3"
